#!/bin/sh
# [Gedit Tool]
# Output=output-panel
# Save-files=all
# Applicability=all
# Shortcut=<Primary>7
# Name=Build+Debug Gradle
# Input=nothing
# Languages=java


EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$GEDIT_CURRENT_DOCUMENT_DIR
FILENAME=/tmp/errors-$(date "+%F-%T").log
while test "$DIR" != "/"; do
    for m in gradlew ; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" | sed "s#$EHOME#~#"
            pushd "${DIR}" > /dev/null
            #./gradlew assembleDebug  2>&1 | grep "error:" | awk '{print $1}' | cut -d ":" -f 1 | uniq
            ./gradlew assembleDebug  2>&1 | grep "error:" | uniq > $FILENAME
            popd > /dev/null
            gedit $FILENAME
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
echo "No Gradle found!" > /dev/stderr
