#!/bin/sh
# [Gedit Tool]
# Output=nothing
# Applicability=all
# Input=document
# Shortcut=<Primary><Alt>r
# Save-files=nothing
# Name=Session Restore

gsettings get org.gnome.gedit.plugins active-plugins | grep dark > /dev/null
if (( $? == 0 )) ; then
    export GTK_THEME=Adwaita:dark
fi
FILE=`zenity --file-selection --title="Restore Session " --filename=$HOME/Projects/Gedit-Sessions/ 2>/dev/null`
if [ ! -z "$FILE" ]; then
	cat $FILE  | xargs gedit --new-window
	echo "Restored Session from " $FILE
fi
