#!/bin/sh
# [Gedit Tool]
# Output=new-document
# Applicability=all
# Input=nothing
# Languages=
# Shortcut=<Primary><Alt>1
# Comment=Execute a custom command and put its output in a new document
# Save-files=nothing
# Name=Run command

gsettings get org.gnome.gedit.plugins active-plugins | grep dark > /dev/null
if (( $? == 0 )) ; then
    export GTK_THEME=Adwaita:dark
fi
#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
eval $(zenity --entry --title="Run Command - gedit" --text="Command to run:")
