#!/bin/sh
# [Gedit Tool]
# Shortcut=<Primary>e
# Name=SearchFile
# Input=nothing
# Output=output-panel
# Save-files=nothing
# Applicability=all

gsettings get org.gnome.gedit.plugins active-plugins | grep dark > /dev/null
if (( $? == 0 )) ; then
    export GTK_THEME=Adwaita:dark;
fi
gnome-terminal -x sh -c "cd $HOME && $HOME/.fzf/bin/fzf | xargs gedit"
