#!/bin/sh
# [Gedit Tool]
# Input=nothing
# Output=output-panel
# Save-files=nothing
# Shortcut=<Primary>t
# Name=TODO-List
# Applicability=all


EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$GEDIT_CURRENT_DOCUMENT_DIR
while test "$DIR" != "/"; do
    for m in gradlew GNUmakefile makefile Makefile; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" | sed "s#$EHOME#~#"
            pushd "${DIR}" > /dev/null
            grep -r "TODO:" $DIR
            popd > /dev/null
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
echo "No Gradle found!" > /dev/stderr
